version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mongo.dockerfile
    expose:
      - "27017"
    ports:
      - "27017:27017" #only for dev
    networks:
      - app-network

  atm-service:
    restart: always
    container_name: atm-service
    build:
      context: ./backend/atm-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network

  auth-service:
    restart: always
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - atm-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
